# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=20, verbose_name='手机号码')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('username', models.CharField(max_length=20, verbose_name='昵称')),
                ('isCustomer', models.BooleanField(default=True, verbose_name='顾客权限')),
                ('isBusiness', models.BooleanField(default=False, verbose_name='商户权限')),
                ('user_join_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('isActive', models.BooleanField(default=True, verbose_name='激活')),
            ],
        ),
    ]
