# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-15 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户基础信息', 'verbose_name_plural': '用户基础信息'},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='UserINFO',
        ),
    ]
