# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20181117_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=35, verbose_name='货柜名')),
                ('windows_num', models.IntegerField(default=20, verbose_name='窗口数量')),
                ('x_adress', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='经度位置')),
                ('y_adress', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='纬度位置')),
                ('store_join_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name_plural': '货柜总表',
                'verbose_name': '货柜总表',
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_id', models.IntegerField(verbose_name='窗口号')),
                ('goods_number', models.IntegerField(default=0, verbose_name='商品数量')),
                ('staring_date', models.DateField(null=True, verbose_name='起租日期')),
                ('end_date', models.DateField(null=True, verbose_name='到期日期')),
            ],
            options={
                'verbose_name_plural': '货柜窗口详情',
                'verbose_name': '货柜窗口详情',
                'db_table': 'Windows',
            },
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo', verbose_name='卖家'),
        ),
        migrations.AddField(
            model_name='windows',
            name='goods_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsInfo', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='windows',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Store', verbose_name='货柜'),
        ),
    ]
