# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20181117_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windows',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='windows',
            name='store',
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo', verbose_name='卖家'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Windows',
        ),
    ]
