# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20181119_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo', verbose_name='卖家'),
        ),
        migrations.AlterField(
            model_name='windows',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.GoodsInfo', verbose_name='商品'),
        ),
    ]
