# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20181119_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='订单号')),
                ('goods_name', models.CharField(max_length=40, verbose_name='商品名称')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('ispay', models.BooleanField(default=False, verbose_name='是否支付')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo', verbose_name='买家')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'db_table': 'ShoppingRecord',
            },
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo', verbose_name='卖家'),
        ),
    ]
