# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-22 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20181122_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo', verbose_name='卖家'),
        ),
        migrations.AlterField(
            model_name='shoppingrecord',
            name='order_number',
            field=models.CharField(max_length=40, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='shoppingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo', verbose_name='买家'),
        ),
    ]
